### ISSUE TITLE
Triblader2 level 99 party member

### ISSUE THREAD

**Issue by PLMMJ-FH** [XenonA7/xenons-playable-classes#11]
Not sure if I should be reporting this on the 'Cord, but I don't use the 'Cord so I'll report it here.
Triblader2 is scaled as if I were at endgame even though I haven't beaten Temple Mine yet as proven by the SP bar in the image.
![CCModBug2](https://github.com/XenonA7/xenons-triblader-mod/assets/159862724/a5e728cb-27e4-43b2-82bb-e1176860ed4c)
Triblader2 is therefore trivializing the game whenever she gets a chance to attack.

**Comment by XenonA7** [comment]
This issue has been reported a few times before, although I have not been able to reproduce it myself. It seems to happen at random but often at different points during Bergen Trail.

By chance, were you using **cc-combat-art-level-extender**? I think the bug might be caused by this mod but I have still not root-caused the issue yet.

**Comment by PLMMJ-FH** [comment]
I am using that mod.

**Comment by XenonA7** [comment]
Still unsure of what causes this, unable to reliably reproduce. However it is **not** caused by commonEvents because it has been documented to happen at a time other than entering a map.

Multiple reports from Discord:

First report:
https://discord.com/channels/991115850146922654/991154606920974427/1063599036113899581

Second report:
https://discord.com/channels/991115850146922654/991154606920974427/1071579479740252180

Third report:
https://discord.com/channels/991115850146922654/991154606920974427/1084373674238427206

Re-creation video:
https://discord.com/channels/991115850146922654/991154606920974427/1099405514749771798
