### ISSUE TITLE
Molten Daggers insta-breaking Digmo

### ISSUE THREAD

**Issue by PLMMJ-FH** [XenonA7/xenons-playable-classes#13]
Molten Daggers is instantly breaking Digmo whenever it turns around and the daggers are in its backside. Same for increased damage on enemies like Horny Goats. Is this intentional? Are the daggers supposed to turn with the enemy?

**Comment by XenonA7** [comment]
Molten Daggers also have a busted interaction with the Designer boss (Blue Avatar). There are quite a few enemies that were obviously not designed with this sort of periodic damage in mind, so there are some odd interactions like this.

Molten Daggers and Daybreak always apply damage in the direction of the projectile stuck in the enemy. Since it doesn't rotate in tandem with the enemy, this can expose a backside weakness when the enemy faces away from the daggers stuck in them. There isn't really a fix for this, it is more of a fundamental design problem with these combat arts.

This current implementation is already a compromise I made from many other previous iterations of the concept, and I think this is not as bad as other problems that are caused without directional damage. I am not planning to change this mechanic.
