### ISSUE TITLE
T2 Neutral guard abilities swapped?

### ISSUE THREAD

**Issue by PLMMJ-FH** [XenonA7/xenons-playable-classes#14]
The guard abilities on T2 are closer to the alternate path's T1 than normal (Deploy Shields has nothing to do with the capabilities of Scattering Shards and shares the defense boost with Blade Aura). I think someone accidentally swapped them in development.

**Comment by XenonA7** [comment]
I did not put them in the same path because they both grant DEF stat increases and I did not want them to both be available for stacking this buff.

Triblader abilities are sort of all over the place, since I this was my first mod. I am sticking to better path themes for Hexacast and future projects. IDK, I might come back and revisit Triblader to rework some combat arts.
